### ISSUE TITLE
List of Orgs on front page, also a direct URL?

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#37]
The list of orgs on the front page is fine, I think, but brings up two questions, here's the first.

Will there also be a direct url for each org to publish or send in email to their ambassadors? Preferably something user-friendly? If not, it isn't a deal breaker (we can tell them to pick their org from the list) but should go on a list for addition at some point.

**Comment by jakelowen** [comment]
Yes.. If you click on any given org it will take you to a dedicated URL for that org...  Typically its in the format of "/org/%org_slug%".  So orgs are currently able to point people either to front page or directly to their url.  Can we close this one?

**Comment by MainStreamDanny** [comment]
Yup, thanks!
