### ISSUE TITLE
List of Orgs on front page, can sign ups be verified by Orgs?

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#38]
If ambassadors sign up by clicking on an organization listed on the home page, is there a way for partners to verify that an ambassador should be an ambassador, and not just some dude in New Jersey who liked the name "El Centro" and thought he'd sign up?

I think this is a pretty critical item, though I suppose we could chase them down manually when they occur, at this point. Partners would have to get in touch and point out they don't know "Kid Rock" from NJ, and could we remove them. But it could get spammy fast if the link gets posted to 4chan or something.

**Comment by jakelowen** [comment]
Thats a good idea and definitely one we can prioritize for our next sprint after most of these other issues are cleared up.  In the meantime hows this for an interim solution.

For every user who is listed as an organization admin, I will put a special dialogue that tells them to directly contact me for any technical assistance. I can manually remove anyone who they don't want affiliated with their org in short order.

**Comment by MainStreamDanny** [comment]
I like it. We should put examples of what they can get addressed by you. Like:

"If you need any technical assistance, please contact <<techhelpinfo>>. This can include changes to your organization details, contact info, your list of ambassadors, etc.

If you need assistance with the Voter to Voter initiative, please contact <<votvhelpinfo>>. This can include policy questions, concerns, or anything else."

Where <<votvhelpinfo>> is, for the moment, "admin@mainstreamcoalition.org" but that might change.

**Comment by MainStreamDanny** [comment]
So, mark this as later and push it off (meaning: the full on org interface to invite, verify, and/or reject ambassadors)? I'm fine with that. Maybe as part of a partner/org dashboard at some point.

**Comment by jakelowen** [comment]
This is encompassed now in #57. Closing this for now.
