### ISSUE TITLE
Need a way to return to personal dashboard, add "Dashboard" to logged in dropdown

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#41]
I tried the logged in name drop down and hit settings, and then tried to get back to my personal page. I can use the back button, but there's no way to click to go back to my dashboard without (I presume) actually changing my password.

I hit the RGOTV button, and it took me out ot the main page again, also with no way to get back to my personal dashboard.

Solution: in the logged in person drop down at the top right, add a link that says "Dashboard" and takes them to their logged in dashboard.

**Comment by jakelowen** [comment]
Added a persistant button to navbar which is available in any view. 

![image](https://user-images.githubusercontent.com/5368008/39213936-80f5881a-47d8-11e8-80b5-aa50a0c3d63b.png)
