### ISSUE TITLE
When there are no contacts, can we fill with verbose instructions?

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#42]
I'd like to have a set of verbose instructions available to the ambassadors. I can write them. I'd like them to be linked from the "Instructions" sidebar item, something like "Click here for detailed instructions." They would be the same for everyone.

But when a new user logs in with "0 Contacts" I'd like to display those verbose instructions on their main page, like a friendlier way to be introduced to your brand new ambassador dashboard. Can we do that? It would be just one file (with graphics, and probably dynamic buttons, like "Add a contact") that could be linked from the sidebar, but also inserted into the otherwise empty space on a virgin dashboard. Like a "Getting Started" document, maybe.

**Comment by MainStreamDanny** [comment]
In connection with another issue I raised (moving the "You have added X contacts:" to the sidebar) this would nicely fill the empty space when they have added no contacts. I really think this would be great.

**Comment by jakelowen** [comment]
![image](https://user-images.githubusercontent.com/5368008/39212838-7bf3b1a0-47d5-11e8-87bd-58cfca1f3bde.png)

Alright @MainStreamDanny - space has been carved out.. put your new text here at your convenience.

**Comment by jakelowen** [comment]
@MainStreamDanny - The above is displayed when a user has 0 contacts. If they have at least 1 contact, it then says "Your contacts"

![image](https://user-images.githubusercontent.com/5368008/39212987-eb118ea4-47d5-11e8-9af8-63420275b352.png)

Do you still want a count in the sidebar?

**Comment by MainStreamDanny** [comment]
No, actually, it would be okay with me if the "at least one contact" text said "You have added X contacts:" The contextual change from none to some works for me, and this would keep the sidebar cleaner, which is always good.

**Comment by MainStreamDanny** [comment]
For clarity, I'm going to go ahead and close this item. I'll open another when i have text to add in that space. I've made myself a not in my own task manager. Thanks!

**Comment by jakelowen** [comment]
@MainStreamDanny - As I'm writing this we are sitting at black dog.. When you reopen as per above can you make sure to capture our notes that whatever text should be able to be revisited later in prompt that lives above sidebar? Above contact list?

**Comment by MainStreamDanny** [comment]
Yes, will do. Am sort of saving this for Lindsay to write, and/or for when we have our own fork. But I can provide some filler or boilerplate for the open source edition, yes.
