### ISSUE TITLE
Move "You have added X contacts" to sidebar

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#43]
I've added four contacts, but the top of my personal dashboard still says "You have added 0 contacts:"

I'm guessing that's because I have not matched any of them up to a voter file, but I think it could be confusing. I'd like to suggest that this be moved and demoted to the sidebar. Perhaps right above the "Add new contact" button. In regular sized text it could read, "You have added 0 contacts:" or "You have added 4 contacts:" and not be concerned with whether they are matched or not.

**Comment by jakelowen** [comment]
@MainStreamDanny - also please review this issue again after viewing newly deployed version in addition to #42 and #44

**Comment by MainStreamDanny** [comment]
You are correct, no longer need it moved to the sidebar, given the changes in 42 and 44. Closing now.
