### ISSUE TITLE
Replace "You have added X contacts" with "These are your contacts:"

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#44]
It might be nice to have something more contextual, but for now, when they do have contacts, we could simply have the same size text say "These are your contacts:"

(When they don't have contacts, I'd like to display the "Getting Started" document I've noted in other issues.)

**Comment by jakelowen** [comment]
@MainStreamDanny - Can you review the live version I just deployed and let me know your new thoughts between this issues and #42.  I'm unclear if you still want it in the sidebar after my latest changes.

**Comment by MainStreamDanny** [comment]
Nope, this is good. Consider it closed.
