### ISSUE TITLE
Voter search for "Sarah" did not find "Sara"

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#46]
Just letting you know that a search for voter "Sarah" "Aitken" "Prairie Village" produced the no matches result, but "Sara" "Aitken" "Prairie Village" worked.

**Comment by MainStreamDanny** [comment]
I'm guessing the voter file matching search is not fuzzy? I tried "Danny" "Novo" Prairie Village" with no results, which is understandable. But "Bob" "Novo" "Prairie Village" matched no records either, when the record is under "Robert" "Novo" "Prairie Village".

This could be a problem when people who really do use their nicknames are the subjects of a search, like "Danny for "Daniel" or "Beth" for "Elizabeth" or "Jack" for "John". I don't think we need to hit all the edge cases, and I guess I was hoping there was some sort of existing library that could be incorporated, because I can see it would be a pain in the ass to create from scratch.

So I guess I'm asking if this is possible, or if it is just something we have to deal with because of the vagaries of personal names and official names.

**Comment by jakelowen** [comment]
Hmm.. Currently every search is a "starts with" type query.  So "Sar" would match "Sara", "Sarah", "Sarasota".. and so on.  Presumably this is possible to load in a list of common name variations but I would need to research / study.  I don't think this is a quick fix, so we might brainstorm some additional guidance via instructions to the user.

**Comment by MainStreamDanny** [comment]
Got it. That makes sense. Yes, then some language during the search might be appropriate. I'll start a new issue with some suggested text. Maybe mark this "Later" for the fuzzier search possibilities?
