### ISSUE TITLE
Display voter file info for matched contacts

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#50]
Once matched, contacts should display their voter file info. It could read

**Danny Novo**
5203 W 80th Ter, Prairie Village, KS

Or it could be visible with a button ("View" or an eyeball instead of the pencil-and-paper "Edit")

This will help identify the contact, and solidify their identity to the user. It will be useful if the match is incorrect (currently there is no way to surface the voter file info for a matched contact).

**Comment by jakelowen** [comment]
@MainStreamDanny - If you click on the button that turns green after the voter has been matched it should show you the matched record and give you the option to unmatch it if desired. Can we tweak something to make that option more apparent?

**Comment by MainStreamDanny** [comment]
Ah, I see that now. It would be a little more obvious if the cursor turned to a clicky finger when hovering over it. But it would be even better if there were tiny text under it that said "Click for data." Oh! They are all buttons. All the hidden data! Yeah, the UI needs to be more obvious. I'll make a new issue for that. In the meantime, I still think some more verbose visible data would be nice, so replacing the Name displayed with the official name of record, and the city with the address and city (maybe truncated if it is too long?) and linked to the "Voter? Yes" display for full data viewing.
