### ISSUE TITLE
New text for no match found

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#52]
Currently, the no match found text says:

"Sorry, No voters match this search

As of 2018-03-20 no voters match this search criteria. That may mean:

1. You may have mispelled something? Review, edit, and try again?
2. If you are searching for someone who may have registered in the last about 1 month, they would not be found here, yet. Check back later. We tend to update voter info about once per month.
3. This person may not be registered to vote. Please refer them to KsVotes.org as an easy way to register. Alternatively you can help them download, print and return the Federal Voter Registration Form. Instructions are included in the form."

I'd like to change that (or suggest we change that) to:

**Sorry, no voters match this search.**

1. Review your search terms. Check spelling, try "Robert" for Bob, and make sure of their city.

2. If they are not registered to vote, they will not be listed in the voter file. Return to your dashboard and take the "Register this voter" action for them.

3. If they have registered to vote recently, they may not be in the latest file, dated <<voterfiledate>>. Try again at a later date. We update the voter file monthly, and more frequently as the election nears.

**Comment by MainStreamDanny** [comment]
Okay, so pursuant to #46 , edit the suggested changes above to read:

**Sorry, no voters match this search.**

1. Review your search terms. Check spelling, try "Robert" for Bob, or "Sar" for Sarah and Sara, and make sure of their city.

If they are not registered to vote, they will not be listed in the voter file. Return to your dashboard and take the "Register this voter" action for them.

If they have registered to vote recently, they may not be in the latest file, dated <>. Try again at a later date. We update the voter file monthly, and more frequently as the election nears.

**Comment by jakelowen** [comment]
@MainStreamDanny - Can you review this issue with a fresh set of eyes and close if possible? So much has changed since this was opened that I don't know if this is still relevant or not.

**Comment by jakelowen** [comment]
Going ahead and closing this. I assume you will review all copy again post-fork.
