### ISSUE TITLE
BIG ONE: Can't see a partner org dashboard, is there one?

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#53]
This is a pretty critical part of the project, and has been from the beginning. At the initial meeting at Panera, we spoke about partner organizations being able to see how their cohort of ambassadors is doing, and being excited to be able to use that data in their communications, grant writing, etc.

I'm just working through the ambassador/user interface right now. Is there a partner interface? I know we decided, for expediency, to have partner orgs created by an admin (you?) once they have signed up with us, so there's no need for a sign up interface for them (though that would be great for the next phase). But a dashboard to track their ambassadors and the voters is pretty crucial.

**Comment by jakelowen** [comment]
Not currently. As we discussed previously, partner orgs would have access to their data by use of Heroku dataclips, which will give them real time access to any custom query we wish including but not limited to ambassadors who have signed up, ambassador progress / points / voters registered and so on. See an example dataclip here: https://dataclips.heroku.com/vgyygvzqtezwpmwpcmmjlluamjlk 

Future versions can move towards an integrated dashboard, but I don't think it's in scope for at least the next month or so.

**Comment by jakelowen** [comment]
Not yet, but very soon. The reason why I can't provide it now is that currently for this test version I am not hosting the DB on heroku yet..  As soon as we fork off into mainstream specific repo I can add this.

**Comment by MainStreamDanny** [comment]
Understood. It's the thing Brandi will ask me about today, and the thing our new hire will want to see on Wednesday, but I can put them off with "technical reasons." The book example won't give them a very clear idea of what partners will get.

**Comment by jakelowen** [comment]
I would describe it this way to them.  "They will have access to a page that looks like this example that will alllow them to view or download data for their org."  The data we allow them to view / download can be whatever we want to give them access to from the database.  I guess the most important question for you guys to discuss internally is "What do we want them to have access to?"  If you guys can help provide clarity on that, it should be trivial to write the queries to satisfy those and turn them into dataclips.

**Comment by MainStreamDanny** [comment]
But basically, the thing to communicate to Brandi et al. is that partners will get link to a .csv download (or something like it) they can open and manipulate. Yes?

**Comment by jakelowen** [comment]
Yes. The url will allow them to view in tabular format and they can take the additional step to download the data in a variety of formats (xls, csv etc)

**Comment by MainStreamDanny** [comment]
Sweet. Okay. I'm going to close this and open a new one as a task to provide an example relevant to VOTV. I'll suss out some fields and post them there.
