### ISSUE TITLE
Make button UI more obvious in a contact's line (Voter? TODO, etc.)

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#55]
Besides the cursor hover, it would be great if the buttons looked more like buttons. The UI for the whole project is pretty flat, so I see where it followed. But the grey label and colored answer make it look like a toggle (like we have become accustomed to on mobil interfaces), not a button. Like it might be informational.

Suggestion: Maybe something as simple as a colored border around both elements, the color of the action? So a green border around the outside of "Voter? Yes" and a red outline around the outside of "TODO: 3"? That might be the easiest change from a CSS standpoint (depending on how the elements cascade).

Even so, it is still not clear why you'd click on "Voter? Yes". It just seems like a status message, not a gateway to more information. Maybe a column header that says "Click for data" or a tiny text line under the button that says the same thing?

**Comment by jakelowen** [comment]
@MainStreamDanny  - Before I fully implement this...  You thinking something like this? (see screencast gif below)

http://g.recordit.co/SooKB0oGKO.gif

**Comment by jakelowen** [comment]
BTW @MainStreamDanny - The currently deployed version button outlines are dumb and wonky.  The outline colors dont switch as they should, and the "clickable" range is not yet right..  I did not want to take the time to fully implement this idea until you weigh in.

**Comment by MainStreamDanny** [comment]
So, no I was thinking something morel like the attached screenshot. I played with Safari's web inspector to get the effect in the css, obvs you'd have to find the right selector for the green color. I added the lats line in the css on the right, the border: 1px solid red. I was thinking like that, rather than the larger outlines you have. What do you think?

<img width="1280" alt="screen shot 2018-04-26 at 10 27 03 am" src="https://user-images.githubusercontent.com/38695722/39327463-b9197022-495d-11e8-8a81-74947b62dafd.png">

**Comment by jakelowen** [comment]
@MainStreamDanny - How is this? 

![image](https://user-images.githubusercontent.com/5368008/39334119-03e4245c-4973-11e8-8435-f5d72cfd3fec.png)

Border color is red/green depending on success/danger status. Background of label is white, but on hover it changes background color to the status color (red/green).  This makes it look and act more like a button.

That work for you?

**Comment by MainStreamDanny** [comment]
Ha! Got it.
