### ISSUE TITLE
Users who are org admins, can we put special info on their page?

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#57]
So, in #38 you imply that org admins are also users on the system. And you suggest you could push a special message to them on their dashboard. Is that what you meant? Because if so, there are a couple of things I'd like to put on there (beyond the help info referenced in #38 ).

Like the link to their heroku data, but also other things I'll outline below if this is true. :)

**Comment by jakelowen** [comment]
Yes. Outline away.

**Comment by MainStreamDanny** [comment]
Okay, here are my initial thoughts.

"Thank you for being the registered contact for <<OrgPartnerName>>. Here are some important links:

1. <<link>>See and download>> the results of your organization's ambassadors.
2. For technical assistance, contact <<techhelpinfo>>. This can include changing your organization's contact info, editing your list of ambassadors, bugs or other concerns.
3. For program assistance, contact admin@mainstreamcoalition.org. This can include policy questions, assistance finding ambassadors, messaging help, or anything else.

You are also invited to be an ambassador! Add contacts and make a difference!"

Something like that?

**Comment by MainStreamDanny** [comment]
Feel free to make me an org contact for ACME (if there can be more than one, or make a new org if not?). Then I can help test it out.

**Comment by jakelowen** [comment]
@MainStreamDanny - For speed I am not going to add links to the admin reporting database "dataclips" to the app itself yet. We can share those via an email to the org admin or via google doc outside of the app itself.

I'll limit the admin conditional text to just the 3 points above.

**Comment by jakelowen** [comment]
@MainStreamDanny - ignore above note.. I decided to implement the org admin section as a freeform markdown renderer. So we can actually display any text including dashboard links. Preview:

![image](https://user-images.githubusercontent.com/5368008/39724398-4a5c5690-520e-11e8-8ad7-789a51d98c73.png)
