### ISSUE TITLE
Cool idea: generate a Voting Commitment Rating

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#58]
It would be totally frwaking awesome if, when a contact is matched to a voter file, it would pull info on their voting history. This could just go into a textarea-style field viewable with the "Voter? Yes" button, or it could be parsed and the voter given a Voting Commitment Rating (VCR, bringing back the old acronyms!) that would be listed with them. Fewer points for snagging a high VCR voter, more points for turning a low VCR voter into a high VCR voter. Or something.

Phase 2? 3?

Looking even further down the line, what if any voter could come to a site and look up their own VCR? And if they get it above some threshold, they get a free ice cream (or something)! Okay, don't get distracted, but this would be an awesome (and separate) project, no? Definitely with nationwide appeal, too.

**Comment by jakelowen** [comment]
Very interesting and doable. Can you give me an example of different VCR scenarios?  i.e.

"John voted in .... but did not vote in ....., so we assign him a VCR of ..."

**Comment by MainStreamDanny** [comment]
This way have some added relevancy to the current year plan, as Brandi and Lindsay are interested in being able to compare voters from this year, with our effort, to their actions in past years. So, it would be nice to say "Our efforts turned a voter who never voted in primaries into a primary voter!" I'll open a new issue for that.

In the meantime, yeah, a VCR score would be cool. As for a possible scale... 1-10? A percentage? Something made up? Not sure.

Some voters are older than others, so have had more opportunities to vote. Younger voters should not be penalized for this, so it shouldn't be an absolute number (John voted ten times over 40 years, has ten points, Beebs voted 4 times in 4 years, only has 4 points). So a percentage of votes taken over opportunities to vote seems better.

We contend at MainStream that primaries are as important as general elections, so those votes should be weighted the same.

We contend that early voting is better than voting at the polls, but voting is all good, so early votes should have slightly more weight than day-of votes.

We like people who are very engaged, so voting outside of primary/general is a bonus, but if they vote in one special election and don't vote in primaries/generals (because they are just really passionate about mandating house colors in their neighborhood, but don't care about anything else) then they shouldn't get extra credit, so maybe "other elections" gives them a small boost, too. But if it is a percentage of all votes, that would probably hurt regular election voters a lot.

So... 90% of their VCR comes from primary/general turnout? 10% comes from "other elections". I'm sort of using a grading scale for this. If they vote in every general and primary but nothing else, they get 90% (A-). Seems okay, but maybe a bit low. 95% comes from primary and general elections, 5% from other. You can get an A by being a regular voter, but only an A+ by being extra involved. Sounds right.

But in this schema, if you only vote in general elections, you'll only hit 47.5%. On a grading scale that's well into F territory, so maybe not a grading scale. Because we do want them to vote, it's not like they should be failing if they vote in general elections.

So, we work out a percentage: general is 47.5% of your score. primaries are 47.5% of your score. Other elections are 5% of your score.

The results are like this: 100-95% is amazing an stellar. 85-94% is a really good voter who has only missed some votes. 48-84% is a good, involved voter who votes in more than half of opportunities. 24-47% are voters who don't vote in every election, but some. 1-23% are voters, but poor voters. 0% (but registered to vote) are losers. Unregistered are just that.

**VCR score**
A+ = 96-100 (every primary and general, and some other)
A = 85-95 (almost every primary and general)
B = 48-84 (over half of every primary and general)
C = 24-47 (less than half of every primary and general)
D = 1-23 (less than half of primaries or generals)
F = 0 (luser)

I kinda dig it as a starting point.

**Comment by jakelowen** [comment]
Closing this and focusing instead on #79
