### ISSUE TITLE
Prevent user from associating 2 PV's with the same voter file record?

### ISSUE THREAD

**Issue by jakelowen** [gpsimpact/relational_gotv#6]
This may be a 2.0 feature.

**Comment by MainStreamDanny** [comment]
Can you explain this to me? As it stands, can users add two contacts and associate them with the same voter file match? If that's what this is, I agree it should be dealt with eventually, but is mostly a problem for preventing people from gaming the system. "I found a great voter, and I'm going to add him ten times and get all the points!" If it's something else let me know?

**Comment by MainStreamDanny** [comment]
Ha! I just verified by adding myself twice to my contact list and matching me twice. I'm going to have ALL THE POINTS! 😀
