### ISSUE TITLE
Can we make the voter match search work with only last name?

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#69]
One of our testers asked if we could just search for "Novo" to find people with weird first names, like "Robert" instead of Danny. I like the idea. DO you?

**Comment by jakelowen** [comment]
Sure.. we could give that a shot.  Do you want to allow city to be optional as well?   My only (slight) concern is for very very common last names.  Smith, Jones.  Having at least city will at least provide a more manageable set of results.
