### ISSUE TITLE
Change VBM to Voted Early

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#70]
The step is "Get them to vote before election day" and it can be accomplished by registering to vote by mail and voting by mail, or by going to an early polling location and voting.

**Comment by jakelowen** [comment]
"VBM" is supposed to indicate if they are currently registered to vote by mail.  "Voted?" indicates whether they have actually cast ballot via any method. (mail, early-in-person, election day etc).

I think its really important to have a status indicating whether someone has filled out the https://www.kssos.org/forms/elections/AV1.pdf form or not.

Perhaps some kind of label change to make this more clear?

**Comment by MainStreamDanny** [comment]
Maybe we should bring Lindsay in on this, at least for another perspective? Maybe we can have it on the agenda for our meeting next week? Or could we get her access here? And to the app. You don't need to do anything special in either place, right? She just signs up?

**Comment by jakelowen** [comment]
Sounds good. Let's wait for Linsday input.

**Comment by MainStreamDanny** [comment]
So, at the meeting we decided to keep it as "VBM?" Good to go.
