### ISSUE TITLE
They should get points for adding at least 10 contacts

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#71]
Just thinking through the scoring a little. Adding ten (or more) contacts should get you points. "Completing" at least 10 or so should get you more points. Can we keep a list of point ideas somewhere? Google Drive?

**Comment by jakelowen** [comment]
A bit tricky but achievable. I may need to rework the api to handle points differently if we get into deep conditional things like this.  @MainStreamDanny - Go ahead and start a google doc and invite me to it where we will brainstorm point events.
