### ISSUE TITLE
Rethinking status versus tasks/TODO...

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#74]
Not exactly an issue, but want to get it out there.

The row of four items for each Contact is now:

Registered? VBM? TODO Voted?

Three of those are status items, are they a registered voter, are they on track to be an early voter, have they voted, yes/no. The fourth, the TODO is different. It feels like it needs a different UI paradigm. Still a button that opens to more info, or to the next task, or something...

Here is a suggestion, see what you think:

- Rename TODO to "Tasks"
- Put it first in the row of four buttons.
- Have it read "Tasks 5/6" for 5 left of 6 total.
- Clicking on it opens the dialog like it does now, but is a UI with accordion style choices. Task 1 opens by default, when they have not completed it, and below it (when they scroll) they can see the titles of the future tasks, but can't open them. Task 1 has text, links, etc. and a checkbox for them to indicate they have completed it. When they do, Task 2 becomes available to open. If they exit and come back, Task 2 opens by default (Task 1's title visible above it, maybe with "Completed" appended, and openable so they can see what they have done, and/or uncheck it?). And so on.

Does that make sense?

**Comment by jakelowen** [comment]
I'm leaning against the accordion interface idea right now just because that interface proposal denotes a fixed number of tasks. I think that may be true for mainstream, but I think the current interface of only displaying the "next task" only makes this tool more conducive to dynamic tasks. I.e. if we decide to add an extra task on the fly for only a subset of voters.

**Comment by jakelowen** [comment]
Explore idea of task dependency.. I.e. task 5 is not eligible until task 3 is complete. Explore non-sequential according ui for tasks.

**Comment by MainStreamDanny** [comment]
I'm just going to add some thoughts Lindsay and I had this morning to inform your development.

As outlined on the points discussion Google doc, and in the development so far, there are two kinds of tasks:

1. Big ones that are verifiable and get status buttons in the interface.
2. Small ones that are self-reported and do not show in the Dashboard (except as points for that contact)

The big ones are:

"Registered to vote" when they are matched to the voter file - 1 pt.
"Applied for mail-in ballot" when they submit the application - 5 pts.
"Voted early" when a vote is recorded in any way before election day - 5 pts.
"Voted" when a vote is recorded in any way - 10 pts.

And, of course, the last three are doubled for General and Primary.

Then we have other tasks we are still developing, but for development, lets use:

"Send an introductory message" - 1 pt.
"Ask them to sign the voting pledge" - 1 pt.

**Comment by MainStreamDanny** [comment]
It occurs to me you've talked about the format being very easy and flexible. Would you like me to submit tasks in the format you've outlined? If yes, remind me where I can find the format example, and I can give it a shot.

**Comment by jakelowen** [comment]
@MainStreamDanny Here is where task definitions are stored:  https://github.com/gpsimpact/relational_gotv/tree/master/src/server/src/taskDefinitions

The "exampleFormSchema.json" is the reference. Alpha, beta, Charlie etc are example implementations.

Be advised that #83, #84, and #85 will necessitate slight revisions to the schema.  Only #83 will be a breaking change as we eliminate <P> elements in favor of moving to markdown.  #84 and #85 will just be the addition of 2 new elements.

Feel free to take a stab. If you don't like working in Schema you can also just sketch them out in a doc and I'll help translate over to definition schema.
