### ISSUE TITLE
Need to compare voters to their past performance

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#75]
So, Brandi and Lindsay are both very interested in being able to compare voters in the program to their past performance. It doesn't have to be in the moment (so this isn't a launch requirement) but they'd like to be able to say that a voter (or a cohort of voters) did or did not exceed their past voting predilections.

Not sure how to accomplish this, but I thought an important first step, and one you should consider adding sooner rather than later, would be to collect their past voting data from the voter file (though I guess that could be done at any time from whatever the most recent file is).

The VCR thoughts we're having in #58 are relevant, obviously, but may be too involved. And the reporting fields in #59 would need to include those, probably (though a simple VCR field would be better, eventually).

Thoughts?

**Comment by jakelowen** [comment]
This is possible, but is more an analytics / evaluation task and not app requirement per se. The app will definitely generate the data necessary to perform this analysis down the road. Because It is not a UI / app requirement I am going to go ahead and close but lets revisit later.

**Comment by MainStreamDanny** [comment]
Got it. Will do.
