### ISSUE TITLE
Segment primary and general, with two sets of VBM and Voted? status buttons

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#76]
Add another line to the status button interface, so that there are two lines:

Primary:   VBM? No     Voted? No
General:   VBM? No     Voted? No

Should make sure they stay together, and don't wrap, so the labels stay with their respective buttons.

**Comment by jakelowen** [comment]
@MainStreamDanny - 

Work in progress.. How does this look:

![image](https://user-images.githubusercontent.com/5368008/39651272-dc5fd374-4fb0-11e8-9015-d294d1c0541c.png)
