### ISSUE TITLE
Points for 10 contacts should be either/or, not cumulative

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#80]
Right now, ambassadors get 1 point per contact added.

I'd like to switch that to 10 points for 10 or more contacts, and zero points for less than 10 contacts.

Can we do that?

If they have 2 total contacts = 0 points
9 contacts = 0 points
10 contacts = 10 points
12 contacts = 10 points
100 contacts = 10 points

No extra points for overachievers.

**Comment by jakelowen** [comment]
@MainStreamDanny - Can you verify this is not already how it works? On commit 4f1581f61c2414f5c90d187c5cf509cca0827e00 I significantly revised the points query to bake in that 10 point bonus. When reviewing that query revision (see line 55 of https://github.com/gpsimpact/relational_gotv/commit/4f1581f61c2414f5c90d187c5cf509cca0827e00#diff-0d7e2c9871e3cba93aceeb2a043f92d5R55) it occurs to be that I might have unintentionally done exactly that above.

**Comment by MainStreamDanny** [comment]
You are correct. I was confused by the fact that I also get one point for matching them. I was adding, then matching, and seeing a point added. My bad. I just added ten contacts without matching them, and got ten points only when I added the tenth. Thanks, Jake.
