### ISSUE TITLE
Welcome instructions for new ambassadors when no contacts present

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#81]
Here's some text for the generic message to appear when dashboards have no contacts on them. When they do, a link to this content (in a separate, static page, or in a dialog) should appear above the contacts list to the effect that "Click here for instructions and help"

Here is the starter text: (Removed and replaced in the next comment)

**Comment by MainStreamDanny** [comment]
We need to add some language about non-partisanship. So, here is revised text. You can juts use this instead of what is above, I've copied the whole thing to make it easy.

"Welcome to this non-partisan relational advocacy tool. Thank you for agreeing to reach out to your family, friends, and community to help engage them in voting. There is no more effective get out the vote effort than people getting the people they know to vote.

This tool revolves around your contacts. When you add a contact, you will be presented with a list of tasks for that person. Some are pretty critical: registering them to vote, getting them to request an advance ballot, and getting them to vote. Others are engagement tasks along the way to those milestones. As you complete tasks, you will receive points, so you can see how you're doing.

We encourage you to list at least ten people you know, and take the first step: matching them up to the public voter file. If you can't find a match, we have instructions for checking for errors or getting in touch to see if they are registered to vote, and registering them if they are not.

In the end, you make all the difference. Your enthusiasm, your dedication to creating a culture of voting will convince your circle to get out and become engaged, too. Thank you."

**Comment by MainStreamDanny** [comment]
We will need different copy once we have forked the tool. We will have some specific MainStream info to disclose.

**Comment by jakelowen** [comment]
Adding above when no contacts are present now and will close the issue. The other half of this request has been added to #87
